[build]
  publish = "dist/public"
  command = "npm run build:netlify"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NETLIFY = "true"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
